{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gateway-application.fullname" . }}
  labels:
    {{- include "gateway-application.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gateway-application.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: frontend
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
    {{- range .Values.networkPolicy.allowedNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ . }}
      ports:
        - protocol: TCP
          port: {{ $.Values.service.port }}
    {{- end }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: fys
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector:
            matchLabels:
              name: stok
      ports:
        - protocol: TCP
          port: 8080
{{- end }} 