{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway-application.serviceAccountName" . }}
  labels:
    {{- include "gateway-application.labels" . | nindent 4 }}
{{- end }} 