replicaCount: 1

image:
  repository: gateway-server
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: gateway.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleDownDelaySeconds: 300
  scaleUpDelaySeconds: 0

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

serviceAccount:
  create: true
  name: ""

networkPolicy:
  enabled: true
  allowedNamespaces:
    - "frontend"
    - "fys"
    - "stok"
    - "config"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "prod"
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
    value: "fys-service"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
    value: "http://fys-service.fys.svc.cluster.local:8080"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
    value: "Path=/api/fys/**"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
    value: "stok-service"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
    value: "http://stok-service.stok.svc.cluster.local:8080"
  - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
    value: "Path=/api/stok/**"
  - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED
    value: "false"
  - name: SPRING_CLOUD_KUBERNETES_CONFIG_ENABLED
    value: "false"
  - name: SPRING_CLOUD_KUBERNETES_ENABLED
    value: "false"

config:
  application:
    name: gateway-service
    server:
      port: 8080
    spring:
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: config-service
              uri: lb://config-application
              predicates:
                - Path=/config/**
            - id: fys-api
              uri: lb://fys-api
              predicates:
                - Path=/fys/**
            - id: stok-api
              uri: lb://stok-api
              predicates:
                - Path=/stok/**

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3 